/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDemoRouteImport } from './routes/_authenticated/demo'
import { Route as AuthenticatedFindRouteImport } from './routes/_authenticated/find'
import { Route as AuthenticatedImpactRouteImport } from './routes/_authenticated/impact'
import { Route as AuthenticatedMyRidesRouteImport } from './routes/_authenticated/my-rides'
import { Route as AuthenticatedOfferRouteImport } from './routes/_authenticated/offer'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRidesRideIdRouteImport } from './routes/_authenticated/rides.$rideId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoRoute = AuthenticatedDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindRoute = AuthenticatedFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpactRoute = AuthenticatedImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRidesRoute = AuthenticatedMyRidesRouteImport.update({
  id: '/my-rides',
  path: '/my-rides',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfferRoute = AuthenticatedOfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRidesRideIdRoute =
  AuthenticatedRidesRideIdRouteImport.update({
    id: '/rides/$rideId',
    path: '/rides/$rideId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/find': typeof AuthenticatedFindRoute
  '/impact': typeof AuthenticatedImpactRoute
  '/my-rides': typeof AuthenticatedMyRidesRoute
  '/offer': typeof AuthenticatedOfferRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rides/$rideId': typeof AuthenticatedRidesRideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/find': typeof AuthenticatedFindRoute
  '/impact': typeof AuthenticatedImpactRoute
  '/my-rides': typeof AuthenticatedMyRidesRoute
  '/offer': typeof AuthenticatedOfferRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rides/$rideId': typeof AuthenticatedRidesRideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demo': typeof AuthenticatedDemoRoute
  '/_authenticated/find': typeof AuthenticatedFindRoute
  '/_authenticated/impact': typeof AuthenticatedImpactRoute
  '/_authenticated/my-rides': typeof AuthenticatedMyRidesRoute
  '/_authenticated/offer': typeof AuthenticatedOfferRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rides/$rideId': typeof AuthenticatedRidesRideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/find'
    | '/impact'
    | '/my-rides'
    | '/offer'
    | '/profile'
    | '/rides/$rideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/find'
    | '/impact'
    | '/my-rides'
    | '/offer'
    | '/profile'
    | '/rides/$rideId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/demo'
    | '/_authenticated/find'
    | '/_authenticated/impact'
    | '/_authenticated/my-rides'
    | '/_authenticated/offer'
    | '/_authenticated/profile'
    | '/_authenticated/rides/$rideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/find': {
      id: '/_authenticated/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof AuthenticatedFindRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impact': {
      id: '/_authenticated/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof AuthenticatedImpactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-rides': {
      id: '/_authenticated/my-rides'
      path: '/my-rides'
      fullPath: '/my-rides'
      preLoaderRoute: typeof AuthenticatedMyRidesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offer': {
      id: '/_authenticated/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof AuthenticatedOfferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rides/$rideId': {
      id: '/_authenticated/rides/$rideId'
      path: '/rides/$rideId'
      fullPath: '/rides/$rideId'
      preLoaderRoute: typeof AuthenticatedRidesRideIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemoRoute: typeof AuthenticatedDemoRoute
  AuthenticatedFindRoute: typeof AuthenticatedFindRoute
  AuthenticatedImpactRoute: typeof AuthenticatedImpactRoute
  AuthenticatedMyRidesRoute: typeof AuthenticatedMyRidesRoute
  AuthenticatedOfferRoute: typeof AuthenticatedOfferRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRidesRideIdRoute: typeof AuthenticatedRidesRideIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemoRoute: AuthenticatedDemoRoute,
  AuthenticatedFindRoute: AuthenticatedFindRoute,
  AuthenticatedImpactRoute: AuthenticatedImpactRoute,
  AuthenticatedMyRidesRoute: AuthenticatedMyRidesRoute,
  AuthenticatedOfferRoute: AuthenticatedOfferRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRidesRideIdRoute: AuthenticatedRidesRideIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
